// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhRso6Kz3inllXRzZdqowT7H51DZR5WqM',
    appId: '1:327356811799:web:1f5bd03fdc4f846b1eea52',
    messagingSenderId: '327356811799',
    projectId: 'vidpay-5e63c',
    authDomain: 'vidpay-5e63c.firebaseapp.com',
    databaseURL: 'https://vidpay-5e63c-default-rtdb.firebaseio.com',
    storageBucket: 'vidpay-5e63c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0BnRruqjCZTG_c3PdQWUmu9Myd46JTAI',
    appId: '1:327356811799:android:8db801d29e7bb1071eea52',
    messagingSenderId: '327356811799',
    projectId: 'vidpay-5e63c',
    databaseURL: 'https://vidpay-5e63c-default-rtdb.firebaseio.com',
    storageBucket: 'vidpay-5e63c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEPuM-s1Ac36wHvHzrLJUdOC05vjOZ5Jg',
    appId: '1:327356811799:ios:8b02d8c631c203051eea52',
    messagingSenderId: '327356811799',
    projectId: 'vidpay-5e63c',
    databaseURL: 'https://vidpay-5e63c-default-rtdb.firebaseio.com',
    storageBucket: 'vidpay-5e63c.appspot.com',
    iosClientId: '327356811799-89fo49b2futl3auvm9ussfujkctted1u.apps.googleusercontent.com',
    iosBundleId: 'C',
  );
}
